name: PUBLISH

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci --legacy-peer-deps

      - uses: nrwl/nx-set-shas@v4

      # Lint, test, and build affected projects
      - run: npx nx affected -t lint test build

      # Publish libraries (only on push to master)
      - name: Publish Libraries
        if: github.ref == 'refs/heads/master'
        run: |
          LIBS=("core" "antd" "mui")
          for LIB in "${LIBS[@]}"; do
            echo "Publishing $LIB..."
            cd dist/libs/$LIB
            npm publish --provenance --access public
            cd -
          done
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
